init
N1Group/cinematic-front pull request #1
Opened 2024-10-06 13:14 UTC by Daniil-l17

2024-10-11 17:51 UTC, BADtochka requested changes

2024-10-11 17:51 UTC, BADtochka commented on public/Icon (1).png
Иконки в SVG и в отдельный файлик
Добавить компонент Icon
Названия иконок типизировать. 😎

```
export const icon1 = (props) => (
...svg...
)

export const icon2 = (props) => (
...svg...
)
```

2024-10-11 17:51 UTC, BADtochka commented on src/components/Button/index.tsx
Добавить иконки слева и справа от children (iconLeft & iconRight)
Выпилить p (зачем?)

2024-10-11 17:51 UTC, BADtochka commented on src/components/Input/style.tsx
> +			background: 'url("/Icon.png") no-repeat center center / 100%',
Решение не очень, а если контент будет заходить на иконку?
Нужно делать inputwrapper, где можно будет ставить иконки с двух сторон (по аналогии с кнопкой)

2024-10-11 17:51 UTC, BADtochka commented on src/components/Input/style.tsx
> +			background: 'url("/Icon.png") no-repeat center center / 100%',
Архитектура инпута, скорее всего будет такой:
```
/InputTextWrapper
  /Label
  InputWrapper
    /iconLeft
    /input
    /iconRight
  /InputWrapper
  /Description
/InputTextWrapper
```

2024-10-11 17:51 UTC, BADtochka commented on src/components/Message/index.tsx
> +				{isMessageUser ? null : <$MessageAvatar background={avatar ? '#222' : '#3F3D67'} border={`1px solid  ${avatar ? '#373737' : '#2F2E4E'}`} img={avatar ?? '/Icon.png'} />}
Нужно переделать компонент аватара и переиспользовать его

2024-10-11 17:51 UTC, BADtochka commented on src/components/Message/index.tsx
> +						{isMessageUser ? null : <$MessageName>{name}</$MessageName>}
```suggestion
						{isMessageUser && <$MessageName>{name}</$MessageName>}
```

2024-10-11 17:51 UTC, BADtochka commented on src/components/Message/index.tsx
> +						{isSystemMessage ? <$MessageSystem>Система</$MessageSystem> : null}
```suggestion
						{isSystemMessage && <$MessageSystem>Система</$MessageSystem>}
```

2024-10-11 17:51 UTC, BADtochka commented on src/page/Home/Home.tsx
> +			<Header />
Вынести выше, потому что юзается в нескольких местах приложения

2024-10-11 17:54 UTC, BADtochka requested changes

2024-10-11 17:54 UTC, BADtochka commented on src/style/index.css
Убрать в assets

2024-10-11 17:55 UTC, BADtochka requested changes

2024-10-11 17:55 UTC, BADtochka commented on src/provader/QueryClientProvader.tsx
PROVADER BRUH

2024-10-11 19:23 UTC, BADtochka commented on src/components/Message/index.tsx
> +						{isMessageUser ? null : <$MessageName>{name}</$MessageName>}
isMessageUser = isMessageAuthor?

2024-10-14 19:17 UTC, BADtochka requested changes

2024-10-14 19:17 UTC, BADtochka commented on src/components/Button/index.tsx
> +	LeftAndRight?: 'left' | 'right';
PascalCase / camelCase / хуйПоЙмиЧто ?

2024-10-14 19:17 UTC, BADtochka commented on src/components/Avatar/types.ts
> +	ischat?: boolean;
PascalCase / camelCase / хуйПоЙмиЧто ?

2024-10-14 19:17 UTC, BADtochka commented on src/components/Input/index.tsx
> +			{isLabel && <$Label>Label</$Label>}
Чо написал... label Это текстовое значение, от него и появляется компонент

2024-10-14 19:17 UTC, BADtochka commented on src/components/Input/index.tsx
> +			{isDescription && <$Description>Description</$Description>}
Аналогично

2024-10-14 19:17 UTC, BADtochka commented on src/components/Input/style.tsx
> +const $InputWrapper = styled.div<{ width?: string; height?: string }>(
inline типизация

2024-10-16 10:46 UTC, Daniil-l17 commented on src/components/Avatar/types.ts
> +	ischat?: boolean;
PascalCase / camelCase / хуйПоймиCase?

2024-10-16 15:14 UTC, BADtochka approved these changes

2024-10-16 15:15 UTC, merged